"""Seed-scoring utilities.

`alphamo score-seeds` runs each STARTER through the full cascade and
overwrites `exemplar_library.py`'s `*_SCORES` definitions with what the
cascade actually says, so the seed baseline used by milestone calibration
and the proposer prompts is grounded in cascade output rather than
hand-picked numbers. This module owns the file-rewrite logic so it can
be unit-tested against fixture strings without touching the live file.
"""

from __future__ import annotations

import re
from typing import Any

# Match a single `<NAME>_SCORES = Scores(...)` block. The lazy `.*?` plus
# `\n)` anchor ensures we stop at the first `)` that sits on its own line —
# the canonical end of every Scores block in exemplar_library.py.
_SCORES_BLOCK_RE = re.compile(
    r"^(?P<name>[A-Z_]+)_SCORES\s*=\s*Scores\(.*?\n\)",
    re.MULTILINE | re.DOTALL,
)

# The `_STARTER_ROBUSTNESS` constant and its leading explanatory comment
# block become obsolete once each seed carries its own cascade-produced
# robustness. Remove them along with the trailing blank line.
_STARTER_ROBUSTNESS_BLOCK_RE = re.compile(
    r"^# STARTERS robustness is hand-set.*?\n_STARTER_ROBUSTNESS = .*?\n+",
    re.MULTILINE | re.DOTALL,
)


def _format_scores_block(name: str, scores: dict[str, Any]) -> str:
    """Format a Scores block in the style exemplar_library.py uses.

    Handles `robustness=None` for seeds that short-circuited before
    Stage 4 — written literally rather than suppressed so the audit
    trail reflects what the cascade did.
    """
    robustness = scores.get("robustness")
    robustness_str = "None" if robustness is None else f"{robustness:.4f}"
    middle_class = scores["middle_class_accessible"]
    return (
        f"{name}_SCORES = Scores(\n"
        f"    feasibility={scores['feasibility']:.4f},\n"
        f"    structural={scores['structural']:.4f},\n"
        f"    exemplar_similarity={scores['exemplar_similarity']:.4f},\n"
        f"    robustness={robustness_str},\n"
        f"    middle_class_accessible={middle_class},\n"
        f")"
    )


def _header_comment(
    generated_at: str,
    parent_goal_version: str,
    verifier_version: str,
) -> str:
    return (
        "# Cascade-produced seed scores. Generated by `alphamo score-seeds`\n"
        f"# on {generated_at} against cascade configuration\n"
        f"# parent_goal_version={parent_goal_version!r}, "
        f"verifier_version={verifier_version!r}.\n"
        "# Re-run when those versions or the cascade prompts change. Inline\n"
        "# hand-picked values are deliberately avoided — the whole point of\n"
        "# the seed baseline is to reflect what the cascade actually says.\n"
    )


def rewrite_exemplar_library_text(
    original: str,
    new_scores: dict[str, dict[str, Any]],
    generated_at: str,
    parent_goal_version: str,
    verifier_version: str,
) -> str:
    """Replace every `<NAME>_SCORES = Scores(...)` block in `original` with
    the cascade-produced scores in `new_scores`, drop the orphaned
    `_STARTER_ROBUSTNESS` constant and its comment, and prepend a header
    comment to the first remaining SCORES block.

    `new_scores` keys are seed-name uppercase prefixes (e.g. "SATOSHI").
    Strict mode: every existing `*_SCORES` block in the file MUST have a
    matching key in `new_scores`, and every key in `new_scores` MUST
    correspond to an existing block. Either direction's mismatch raises
    KeyError. This protects against (a) typos silently dropping scores
    and (b) the `_STARTER_ROBUSTNESS` constant being orphaned after the
    rewrite — if all blocks are replaced, no block references it anymore.
    """
    blocks_seen = {m.group("name") for m in _SCORES_BLOCK_RE.finditer(original)}
    new_keys = set(new_scores)
    missing_in_file = new_keys - blocks_seen
    missing_in_scores = blocks_seen - new_keys
    if missing_in_file or missing_in_scores:
        msg_parts = []
        if missing_in_file:
            msg_parts.append(
                f"new_scores keys not found as *_SCORES blocks in target file: "
                f"{sorted(missing_in_file)}"
            )
        if missing_in_scores:
            msg_parts.append(
                f"*_SCORES blocks in target file not covered by new_scores: "
                f"{sorted(missing_in_scores)}"
            )
        raise KeyError("; ".join(msg_parts) + f" (saw blocks: {sorted(blocks_seen)})")

    def _replace_block(match: re.Match[str]) -> str:
        name = match.group("name")
        return _format_scores_block(name, new_scores[name])

    rewritten = _SCORES_BLOCK_RE.sub(_replace_block, original)

    # Strip the legacy `_STARTER_ROBUSTNESS` constant + its comment block.
    rewritten = _STARTER_ROBUSTNESS_BLOCK_RE.sub("", rewritten)

    # Prepend the generation-provenance comment ahead of the first remaining
    # SCORES block. Locate the first SATOSHI_SCORES (or any *_SCORES) to
    # anchor the insertion.
    first_block_match = _SCORES_BLOCK_RE.search(rewritten)
    if first_block_match is None:
        # No SCORES blocks remained — nothing to anchor against. Return as-is.
        return rewritten
    insertion_point = first_block_match.start()
    header = _header_comment(generated_at, parent_goal_version, verifier_version)
    return rewritten[:insertion_point] + header + rewritten[insertion_point:]
